### ISSUE TITLE
Assignments?

### ISSUE THREAD

**Issue by dojo-json** [CodingDojo-MEAN-07-18/Jaxon#1]
Where are your assignments?

**Comment by JaxWLee** [comment]
Haha wild timing just uploaded them

**Comment by dojo-json** [comment]
Indeed, thanks for submitting. I recommend closing this issue with your next push.

Check here for more info: https://help.github.com/articles/closing-issues-using-keywords/

**Comment by dojo-json** [comment]
Please push your latest assignments

**Comment by JaxWLee** [comment]
Just pushed an update

**Comment by dojo-json** [comment]
Awesome, thanks

**Comment by JaxWLee** [comment]
I just wanted to confirm we have tell September 10 to turn everything in,
including the exam? I'm doing the full mean assignments but I also just
started a job at Revature and learning Java is apart of the training so I'm
coding almost nonstop and want to make sure I have ample time for
everything.

On Aug 30, 2018 20:24, "Jason" <notifications@github.com> wrote:

Awesome, thanks

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/CodingDojo-MEAN-07-18/Jaxon/issues/1#issuecomment-417510071>,
or mute the thread

**Comment by dojo-json** [comment]
Yes.
